truncate civilization_card cascade;
truncate card_credit cascade;

insert into civilization_card (card_name, face_value, card_type) values
('cloth_making', 45, 'CRAFT'),
('pottery', 45, 'CRAFT'),
('metal_working', 80, 'CRAFT'),
('agriculture', 110, 'CRAFT'),
('road_building', 140, 'CRAFT'),
('mining', 180, 'CRAFT'),
('engineering', 140, 'CRAFT_SCIENCE'),
('astronomy', 80, 'SCIENCE'),
('coinage', 110, 'SCIENCE'),
('medicine', 140, 'SCIENCE'),
('mathematics', 230, 'SCIENCE_ART'),
('drama_poetry', 60, 'ART'),
('music', 60, 'ART'),
('architecture', 120, 'ART'),
('mysticism', 50, 'ART_RELIGION'),
('literacy', 110, 'ART_CIVIC'),
('law', 170, 'CIVIC'),
('military', 180, 'CIVIC'),
('democracy', 200, 'CIVIC'),
('philosophy', 240, 'CIVIC'),
('deism', 80, 'RELIGION'),
('enlightenment', 150, 'RELIGION'),
('monotheism', 220, 'RELIGION'),
('theology', 250, 'RELIGION')
;

insert into card_credit (giver_card_name, receiver_card_name, amount) values
('agriculture', 'cloth_making', 10),
('engineering', 'cloth_making', 10),
('metal_working', 'cloth_making', 10),
('mining', 'cloth_making', 10),
('pottery', 'cloth_making', 10),
('road_building', 'cloth_making', 10),

('agriculture', 'pottery', 10),
('engineering', 'pottery', 10),
('metal_working', 'pottery', 10),
('mining', 'pottery', 10),
('cloth_making', 'pottery', 10),
('road_building', 'pottery', 10),

('agriculture', 'metal_working', 10),
('engineering', 'metal_working', 10),
('cloth_making', 'metal_working', 10),
('mining', 'metal_working', 10),
('pottery', 'metal_working', 10),
('road_building', 'metal_working', 10),

('cloth_making', 'agriculture', 10),
('engineering', 'agriculture', 10),
('metal_working', 'agriculture', 10),
('mining', 'agriculture', 10),
('pottery', 'agriculture', 10),
('road_building', 'agriculture', 10),

('agriculture', 'road_building', 10),
('engineering', 'road_building', 10),
('metal_working', 'road_building', 10),
('mining', 'road_building', 10),
('pottery', 'road_building', 10),
('cloth_making', 'road_building', 10),

('agriculture', 'mining', 10),
('engineering', 'mining', 10),
('metal_working', 'mining', 10),
('cloth_making', 'mining', 10),
('pottery', 'mining', 10),
('road_building', 'mining', 10),

('agriculture', 'engineering', 10),
('cloth_making', 'engineering', 10),
('metal_working', 'engineering', 10),
('pottery', 'engineering', 10),
('astronomy', 'engineering', 20),
('coinage', 'engineering', 20),
('mathematics', 'engineering', 20),
('medicine', 'engineering', 20),

('engineering', 'astronomy', 20),
('coinage', 'astronomy', 20),
('mathematics', 'astronomy', 20),
('medicine', 'astronomy', 20),

('astronomy', 'coinage', 20),
('engineering', 'coinage', 20),
('mathematics', 'coinage', 20),
('medicine', 'coinage', 20),

('astronomy', 'medicine', 20),
('coinage', 'medicine', 20),
('mathematics', 'medicine', 20),
('engineering', 'medicine', 20),

('astronomy', 'mathematics', 20),
('coinage', 'mathematics', 20),
('engineering', 'mathematics', 20),
('medicine', 'mathematics', 20),

('architecture', 'mysticism', 5),
('drama_poetry', 'mysticism', 5),
('music', 'mysticism', 5),
('literacy', 'mysticism', 5),
('mathematics', 'mysticism', 5),

('architecture', 'music', 5),
('drama_poetry', 'music', 5),
('mysticism', 'music', 5),
('literacy', 'music', 5),
('mathematics', 'music', 5),

('architecture', 'drama_poetry', 5),
('mysticism', 'drama_poetry', 5),
('music', 'drama_poetry', 5),
('literacy', 'drama_poetry', 5),
('mathematics', 'drama_poetry', 5),

('mysticism', 'architecture', 5),
('drama_poetry', 'architecture', 5),
('music', 'architecture', 5),
('literacy', 'architecture', 5),
('mathematics', 'architecture', 5),

('mysticism', 'deism', 15),

('deism', 'enlightenment', 15),
('mysticism', 'enlightenment', 15),
('mathematics', 'enlightenment', 10),
('architecture', 'enlightenment', 10),
('drama_poetry', 'enlightenment', 10),
('music', 'enlightenment', 10),
('literacy', 'enlightenment', 10),

('deism', 'theology', 15),
('mysticism', 'theology', 15),
('enlightenment', 'theology', 15),
('astronomy', 'theology', 20),
('coinage', 'theology', 20),
('engineering', 'theology', 20),
('medicine', 'theology', 20),
('mathematics', 'theology', 20),

('deism', 'monotheism', 15),
('mysticism', 'monotheism', 15),
('enlightenment', 'monotheism', 15),
('agriculture', 'monotheism', 10),
('engineering', 'monotheism', 10),
('metal_working', 'monotheism', 10),
('cloth_making', 'monotheism', 10),
('pottery', 'monotheism', 10),
('road_building', 'monotheism', 10),
('mining', 'monotheism', 10),

('architecture', 'literacy', 5),
('drama_poetry', 'literacy', 20),
('music', 'literacy', 5),
('mathematics', 'literacy', 5),
('mysticism', 'literacy', 5),

('literacy', 'law', 25),
('architecture', 'law', 15),

('metal_working', 'military', 20),

('agriculture', 'democracy', 10),
('engineering', 'democracy', 10),
('metal_working', 'democracy', 10),
('cloth_making', 'democracy', 10),
('pottery', 'democracy', 10),
('road_building', 'democracy', 10),
('mining', 'democracy', 10),
('architecture', 'democracy', 10),
('drama_poetry', 'democracy', 10),
('music', 'democracy', 10),
('literacy', 'democracy', 25),

('astronomy', 'philosophy', 20),
('coinage', 'philosophy', 20),
('engineering', 'philosophy', 20),
('medicine', 'philosophy', 20),
('mathematics', 'philosophy', 20),
('music', 'philosophy', 20),
('literacy', 'philosophy', 25)
;